#pragma once

enum RenderLayer
{
	RENDERLAYER_DOUBLE_SIDED,
	RENDERLAYER_BLEND,
	RENDERLAYER_OPAQUE,
	RENDERLAYER_OPTIONAL_ALPHATEST,
	RENDERLAYER_ALPHATEST,
	RENDERLAYER_ALPHATEST_SINGLE_SIDE,
	_RENDERLAYER_COUNT,
};